debug: false
server:
  servlet:
    context-path: /api
  port: 8080
#development environment
---
spring:
  liquibase:
    clear-checksums: true #disable cashing
    change-log: db/changelog/changelog.yaml

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ms_db?createDatabaseIfNotExist=true

#test environment
---
spring:
  config:
    activate:
      on-profile: test-env

  liquibase:
    clear-checksums: true
    change-log: db/changelog/changelog.yaml

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none

  datasource:
    username: h2db
    password: h2db
    url: jdbc:h2:mem:ms_db_test;MODE=MySQL